--- #YAML:1.0
name:                Devel-Command
version:             0.11
abstract:            ~
license:             ~
author:              
    - Joe McMahon <mcmahon@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Module::Pluggable:             0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
