#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-Command
version:      0.08
version_from: lib/Devel/Command.pm
installdirs:  site
requires:
    Test::More:                    0
    Module::Pluggable:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
